apiVersion: apps/v1
kind: Deployment
metadata:
  name: udaconnect-connections-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-connections-consumer
  template:
    metadata:
      labels:
        app: udaconnect-connections-consumer
    spec:
      containers:
      - name: consumer
        image:  pedrosaez/udaconnect-connections:1.0.0
        command: ["python"]
        args: ["run_consumer.py"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-broker:9092
        - name: DB_HOST
          value: postgres