# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'person.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x06person\"X\n\rPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"V\n\x0bPersonReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"2\n\nPersonList\x12$\n\x07persons\x18\x01 \x03(\x0b\x32\x13.person.PersonReply\"\x07\n\x05\x45mpty2\xb8\x01\n\rPersonService\x12\x37\n\tGetPerson\x12\x15.person.PersonRequest\x1a\x13.person.PersonReply\x12\x32\n\rGetAllPersons\x12\r.person.Empty\x1a\x12.person.PersonList\x12:\n\x0c\x43reatePerson\x12\x15.person.PersonRequest\x1a\x13.person.PersonReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONREQUEST']._serialized_start=24
  _globals['_PERSONREQUEST']._serialized_end=112
  _globals['_PERSONREPLY']._serialized_start=114
  _globals['_PERSONREPLY']._serialized_end=200
  _globals['_PERSONLIST']._serialized_start=202
  _globals['_PERSONLIST']._serialized_end=252
  _globals['_EMPTY']._serialized_start=254
  _globals['_EMPTY']._serialized_end=261
  _globals['_PERSONSERVICE']._serialized_start=264
  _globals['_PERSONSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
